// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: dotenv import removed — in production (Docker/Coolify), env vars are injected directly
import { loadEnvConfig } from "@next/env";
import { defineConfig } from "prisma/config";

// Load environment variables from .env files locally
loadEnvConfig(process.cwd());

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Tukar kepada DIRECT_URL khas untuk Supabase migrations
    url: process.env["DIRECT_URL"],
  },
});
